title: Saharsh Gupta
description: Machine Learning Engineer & Full-Stack Developer. Building intelligent systems at the intersection of AI and software engineering.
author: Saharsh Gupta
theme: minima
url: "https://saharshg29.github.io"
baseurl: ""
twitter_username: saharshg29
github_username: saharshg29
google_analytics: "G-XXXXXXXXXX" # User can update this
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap 

permalink: /:collection/:title/

collections_dir: content

collections:
  essays:
    output: true
    permalink: /essays/:title/
  engineering:
    output: true
    permalink: /engineering/:title/
  reflections:
    output: true
    permalink: /reflections/:title/
  journals:
    output: true
    permalink: /journal/:title/