title: Saharsh Gupta
description: Engineering essays and personal reflections.
author: Saharsh Gupta
theme: minima 
url: ""
baseurl: ""
plugins:
  - jekyll-seo-tag 

permalink: /:collection/:title/

collections:
  essays:
    output: true
    permalink: /essays/:title/
  engineering:
    output: true
    permalink: /engineering/:title/
  reflections:
    output: true
    permalink: /reflections/:title/
  journals:
    output: true
    permalink: /journal/:title/